### ISSUE TITLE
Incorrect retryIn?

### ISSUE THREAD

**Issue by pselden** [Losant/redis-gcra#3]
I'm trying to set up a simple password rate limiter, and I want to allow 6 attempts per minute.

I set it up like this:

```js
  const {limited, retryIn} = await limiter.limit({
    key: `signin/email/${email.trim().toLowerCase()}`,
    burst: 6,
    rate: 6,
    period: 60000,
    cost: 1
  });
```

When I do too many sign ins I eventually get a retryIn of 10, but then it gets down to below 5 and then the next request is allowed!

Is this an issue with the rate limiter allowing too many requests through, or an issue with the retryIn?

Or is it an issue in how I'm configuring this?

**Comment by pselden** [comment]
I believe it's probably due to the rounding mechanism, which makes it so it actually refills a token when 50% of the retryIn is remaining.

**Comment by pselden** [comment]
Here's a version that seems to be slightly more accurate:

```
local rate_limit_key = KEYS[1]
local now = ARGV[1]
local burst = ARGV[2]
local rate = ARGV[3]
local period = ARGV[4]
local cost = ARGV[5]

local emission_interval = period / rate
local increment = emission_interval * cost
local burst_offset = emission_interval * (burst + 1)

local tat = redis.call("GET", rate_limit_key)

if not tat then
    tat = now
else
    tat = tonumber(tat)
end

tat = math.max(tat, now)

local new_tat = tat + increment
local allow_at = new_tat - burst_offset
local diff = now - allow_at

local retry_in
local reset_in
local remaining

if diff < 0 then
    limited = 1
    if increment <= burst_offset then
        retry_in = diff * -1
    else
        retry_in = -1
    end
    reset_in = tat - now
    remaining = 0
else
    limited = 0
    retry_in = 0
    reset_in = new_tat - now
    remaining = math.floor(diff / emission_interval + 0.5) -- poor man's round
    if increment > 0 then
        redis.call("SET", rate_limit_key, new_tat, "EX", reset_in)
    end
end

return {limited, remaining, retry_in, reset_in}
```

It's based off of https://github.com/throttled/throttled/blob/master/rate.go

Remaining might still need a little work

**Comment by spacetc62** [comment]
Sorry for the delay, never even noticed the issue filed on here!

I actually ran into this same thing myself, and decided to just get rid of the rounding completely (to be honest, I'm not sure why we were rounding in the first place).

https://github.com/Losant/redis-gcra/pull/4
